### ISSUE TITLE
unexpected keyword argument 'params'

### ISSUE THREAD

**Issue by Soundhar0710** [WoolDoughnut310/micropython-firebase-firestore#1]
I'm getting this error when I run the file.  I got the access token with my firebase API and loaded it on the library but when I try to get the fields I got the following error.

Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "/lib/ufirestore/ufirestore.py", line 229, in get
  File "/lib/ufirestore/ufirestore.py", line 104, in get
  File "/lib/ufirestore/ufirestore.py", line 52, in send_request
TypeError: unexpected keyword argument 'params'

**Comment by deepakgonda** [comment]
I am also getting same error, i think it might be due to b/c we are using latest version of micropython

**Comment by deepakgonda** [comment]
I have checked and found out this b/c urequests.request has different keyworded argument then what is being used.

Change line 51 and 52 as following 

`response = urequests.request(
        method, url=path, data=params, json=data, headers=headers)`
instead of
`response = urequests.request(
        method, path, params=params, headers=headers, json=data)`

It should work.
